trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  displayName: 'Checkout Code'

- script: |
    echo "Starting build and test..."
    START_TIME=$(date +%s)
    npm install
    npm test
    END_TIME=$(date +%s)
    BUILD_DURATION=$(( END_TIME - START_TIME ))
    echo "##vso[task.setvariable variable=BuildDurationSeconds]$BUILD_DURATION"
    echo "Build duration: $BUILD_DURATION seconds"
    if [ $? -eq 0 ]; then
      echo "##vso[task.setvariable variable=TestSuccess]true"
      echo "Tests passed"
    else
      echo "##vso[task.setvariable variable=TestSuccess]false"
      echo "Tests failed"
    fi
  displayName: 'Build and Test'
  continueOnError: true

- script: |
    echo "Packaging application..."
    mkdir -p dist
    cp index.js package.json dist/
    zip -r app.zip dist/
  displayName: 'Package Application'

- publish: $(System.DefaultWorkingDirectory)/app.zip
  artifact: 'app'
  displayName: 'Publish Artifact'

- script: |
    echo "Fetching tasks and updating Estimate Accuracy..."
    echo "PAT_TOKEN is set to: [REDACTED]"
    PROJECT_NAME="Week4-Lab-Demo$STUDENT_INITIALS"
    RESPONSE=$(curl -u :"$PAT_TOKEN" -H "Content-Type: application/json" \
      "https://devopsclassroom.visualstudio.com/$PROJECT_NAME/_apis/wit/wiql?api-version=6.0" \
      -d "{\"query\": \"SELECT [System.Id], [System.Title], [Microsoft.VSTS.Scheduling.OriginalEstimate], [Microsoft.VSTS.Scheduling.CompletedWork] FROM WorkItems WHERE [System.WorkItemType] = 'Task' AND [System.State] = 'Closed' AND [System.TeamProject] = '$PROJECT_NAME'\"}" \
      --silent --show-error)
    echo "API Response: $RESPONSE"
    if echo "$RESPONSE" | grep -q "<html>"; then
      echo "Error: Received HTML redirect, PAT may be invalid or expired"
      exit 1
    fi
    echo "$RESPONSE" | jq -r '.workItems[] | [.id] | join(" ")' > task_ids.txt || { echo "Failed to parse JSON response"; exit 1; }
    for TASK_ID in $(cat task_ids.txt); do
      TASK_DATA=$(curl -u :"$PAT_TOKEN" -H "Content-Type: application/json" \
        "https://devopsclassroom.visualstudio.com/$PROJECT_NAME/_apis/wit/workitems/$TASK_ID?api-version=6.0" \
        --silent --show-error)
      echo "Task $TASK_ID Data: $TASK_DATA"
      ORIGINAL_ESTIMATE=$(echo "$TASK_DATA" | jq -r '.fields["Microsoft.VSTS.Scheduling.OriginalEstimate"] // 0')
      COMPLETED_WORK=$(echo "$TASK_DATA" | jq -r '.fields["Microsoft.VSTS.Scheduling.CompletedWork"] // 0')
      ESTIMATE_ACCURACY=$(echo "scale=2; $ORIGINAL_ESTIMATE - $COMPLETED_WORK" | bc)
      echo "Task $TASK_ID: Original=$ORIGINAL_ESTIMATE, Completed=$COMPLETED_WORK, Accuracy=$ESTIMATE_ACCURACY"
      curl -u :"$PAT_TOKEN" -X PATCH -H "Content-Type: application/json-patch+json" \
        "https://devopsclassroom.visualstudio.com/$PROJECT_NAME/_apis/wit/workitems/$TASK_ID?api-version=6.0" \
        -d "[{\"op\": \"add\", \"path\": \"/fields/Custom.EstimateAccuracy\", \"value\": $ESTIMATE_ACCURACY}]" \
        --silent --show-error || echo "Failed to update Task $TASK_ID"
    done
  displayName: 'Update Task Estimate Accuracy'
  env:
    PAT_TOKEN: $(PAT_TOKEN)
    STUDENT_INITIALS: $(STUDENT_INITIALS)

- script: |
    echo "Pipeline Metrics:"
    echo "BuildDurationSeconds=$(BuildDurationSeconds)"
    echo "TestSuccess=$(TestSuccess)"
  displayName: 'Log Metrics'