trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  displayName: 'Checkout Code'

- script: |
    chmod +x hello.sh
    ./hello.sh
  displayName: 'Run Hello Script'

- script: |
    echo "Pipeline completed at $(date)"
  displayName: 'Log Completion'